apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
      - name: keycloak
        image: quay.io/keycloak/keycloak:21.0.2
        args: ["start"]
        env:
        - name: KC_DB
          value: postgres
        - name: KC_DB_URL
          value: "jdbc:postgresql://doadmin:AVNS_xia0PLucZdQXoLIN9n3@db-postgresql-nyc1-12259-do-user-3558509-0.b.db.ondigitalocean.com:25060/keycloak?sslmode=require"
        - name: KC_DB_USERNAME
          value: "doadmin"
        - name: KC_TRANSACTION_XA_ENABLED
          value: "false"
        - name: KC_DB_PASSWORD
          value: "AVNS_xia0PLucZdQXoLIN9n3"
        - name: KC_DB_URL_DATABASE
          value: keycloak
        - name: PROXY_ADDRESS_FORWARDING
          value: "true"
        - name: JDBC_PARAMS
          value: trustServerCertificate=false;encrypt=false
        - name: KC_DB_URL_HOST
          value: db-postgresql-nyc1-12259-do-user-3558509-0.b.db.ondigitalocean.com
        - name: KC_DB_URL_PORT
          value: "25060"
        # - name: KC_HOSTNAME
        #   value: "25060"
        # - name: DB_DATABASE
        #   value: keycloak
        # - name: DB_USER
        #   valueFrom:
        #     secretKeyRef:
        #       name: keycloak-postgres-credentials
        #       key: POSTGRES_USER
        # - name: DB_PASSWORD
        #   valueFrom:
        #     secretKeyRef:
        #       name: keycloak-postgres-credentials
        #       key: POSTGRES_PASSWORD
        - name: KEYCLOAK_ADMIN
          value: parallelscore
        - name: KEYCLOAK_ADMIN_PASSWORD
          value: BL464W5u17sDGdGI
        - name: KC_HTTP_ENABLED
          value: "true"
        - name: KEYCLOAK_HTTP_PORT
          value: "8080"
        - name: KEYCLOAK_HTTPS_PORT
          value: "8443"
        - name: KEYCLOAK_FRONTEND_URL
          value: "https://keycloak.lafia.io"
        - name: KC_PROXY
          value: "passthrough"
        ports:
        - name: http
          containerPort: 8080
        - name: https
          containerPort: 8443
        readinessProbe:
          httpGet:
            path: /realms/master
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 1
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak
spec:
  selector:
    app: keycloak
  ports:
  - name: https
    port: 80
    targetPort: 8080